### ISSUE TITLE
Error tf Stream

### ISSUE THREAD

**Issue by Burak93** [segway-robotics/vision_msg_proc#5]
after starting to publish Depth Images and Tf, app #crashes.

_Ubuntu 16.04
ROS kinetic
android studio 3.0.1_

Error:
```
org.ros.android.android_tutorial_camera E/Parcel: Class not found when unmarshalling: 
 java.lang.ClassNotFoundException: Invalid name: 
  at java.lang.Class.classForName(Native Method)
  at java.lang.Class.forName(Class.java:306)
  at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
  at android.os.Parcel.readParcelable(Parcel.java:2245)
  at com.segway.robot.algo.tf.AlgoTfData.<init>(AlgoTfData.java:21)
  at com.segway.robot.algo.tf.AlgoTfData$1.createFromParcel(AlgoTfData.java:28)
  at com.segway.robot.algo.tf.AlgoTfData$1.createFromParcel(AlgoTfData.java:25)
  at com.segway.robot.sdk.perception.sensor.IRobotSensorService$Stub$Proxy.getTfData(IRobotSensorService.java:367)
  at com.segway.robot.sdk.perception.sensor.SensorManager.getTfData(SensorManager.java:157)
  at com.segway.robot.sdk.perception.sensor.Sensor.getTfData(Sensor.java:82)
  at org.ros.android.android_tutorial_camera.LoomoRosBridgeNode$SensorPublisherThread.run(LoomoRosBridgeNode.java:417)
```

**Comment by qinyusen** [comment]
hi, update sdk (locomotion), it may solved.
